from pathlib import Path
p=Path('src/CampeonatoConfiguracion.jsx')
s=p.read_text(encoding='utf-8')
old='''<Campo etiqueta="Criterio de cruces"><select name="criterio_generar_cruces" value={config.criterio_generar_cruces} onChange={cambiar}><option>Por Clasificación</option><option>No Enfrentados</option><option>Aleatorio</option></select></Campo>'''
new='''<Campo etiqueta={<span className="etiqueta-con-info">Criterio de cruces <span className="info-criterio" tabIndex="0" role="button" aria-label="Información sobre los criterios de cruces">i<span className="info-criterio-texto"><strong>Por Clasificación:</strong> enfrenta al mejor clasificado disponible con el peor, segundo mejor con segundo peor, etc.<br /><br /><strong>No Enfrentados:</strong> prioriza emparejamientos entre equipos que todavía no hayan jugado entre sí; solo repite cuando no sea posible evitarlo.<br /><br /><strong>Aleatorio:</strong> realiza un sorteo completamente aleatorio entre los equipos disponibles, sin utilizar la clasificación ni los enfrentamientos anteriores.</span></span></span>}><select name="criterio_generar_cruces" value={config.criterio_generar_cruces} onChange={cambiar}><option>Por Clasificación</option><option>No Enfrentados</option><option>Aleatorio</option></select></Campo>'''
if old not in s: raise SystemExit('No se encontró el selector de criterio')
p.write_text(s.replace(old,new,1),encoding='utf-8')

p=Path('src/CampeonatoConfiguracion.css')
s=p.read_text(encoding='utf-8')
css='''\n/* Ayuda contextual del criterio de cruces */\n.etiqueta-con-info { display: inline-flex; align-items: center; gap: .4rem; }\n.info-criterio { position: relative; display: inline-flex; align-items: center; justify-content: center; width: 1.15rem; height: 1.15rem; border: 1px solid currentColor; border-radius: 50%; font-size: .78rem; font-weight: 700; line-height: 1; cursor: help; user-select: none; }\n.info-criterio-texto { display: none; position: absolute; z-index: 50; top: calc(100% + .55rem); left: 50%; transform: translateX(-50%); width: min(320px, 78vw); padding: .8rem .9rem; border-radius: .7rem; background: #111827; color: #fff; box-shadow: 0 8px 28px rgba(0,0,0,.28); font-size: .82rem; font-weight: 400; line-height: 1.35; text-align: left; white-space: normal; }\n.info-criterio:hover .info-criterio-texto, .info-criterio:focus .info-criterio-texto, .info-criterio:focus-within .info-criterio-texto { display: block; }\n@media (max-width: 600px) { .info-criterio-texto { left: 0; transform: none; width: min(280px, 76vw); } }\n'''
if '/* Ayuda contextual del criterio de cruces */' not in s: s += css
p.write_text(s,encoding='utf-8')
