import { useEffect, useMemo, useState } from 'react'
import { catalogoJugadoresTeams, guardarConvocatoriaTeams, obtenerDetalleTeams } from '../teamsApi'
const OPCIONES=[['elegible','Me apunto'],['no_disponible','No puedo'],['pendiente','Todavía no sé']]
export default function Convocatoria({ teams }) {
 const [jugadores,setJugadores]=useState([]),[estados,setEstados]=useState({}),[origenes,setOrigenes]=useState({}),[buscar,setBuscar]=useState(''),[cargando,setCargando]=useState(true),[guardando,setGuardando]=useState(false),[mensaje,setMensaje]=useState(''),[guardado,setGuardado]=useState(false)
 useEffect(()=>{(async()=>{try{const [cat,det]=await Promise.all([catalogoJugadoresTeams(),obtenerDetalleTeams(teams.id)]);setJugadores(cat.filter(j=>j.activo));const es={},os={};for(const e of det?.elegibles??[]){es[e.id_jugador]=e.estado;os[e.id_jugador]=e.origen}setEstados(es);setOrigenes(os);setGuardado((det?.elegibles??[]).length>0)}catch(e){setMensaje('Error: '+e.message)}finally{setCargando(false)}})()},[teams.id])
 const filtrados=useMemo(()=>{const q=buscar.trim().toLowerCase();return !q?jugadores:jugadores.filter(j=>(j.alias||'').toLowerCase().includes(q)||(j.nombre_oficial||'').toLowerCase().includes(q))},[jugadores,buscar])
 const totalElegibles=Object.values(estados).filter(x=>x==='elegible').length, pendientes=Object.values(estados).filter(x=>x==='pendiente').length
 const plazas=(Number(teams.jugadores_por_equipo)||0)*2+(Number(teams.reservas_por_equipo)||0)*2
 function cambiar(id,estado){setGuardado(false);setMensaje('');setEstados(s=>({...s,[id]:estado}));setOrigenes(s=>({...s,[id]:'admin'}))}
 async function guardar(){setGuardando(true);setMensaje('');try{const datos=jugadores.filter(j=>estados[j.id_jugador]).map(j=>({id_jugador:j.id_jugador,estado:estados[j.id_jugador]}));await guardarConvocatoriaTeams(teams.id,datos);setMensaje('Convocatoria guardada correctamente.');setGuardado(true)}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 return <section className="teams-convocatoria"><div className="teams-seccion-cab"><div><p className="etiqueta">CONVOCATORIA</p><h2>Disponibilidad de jugadores</h2><p>El administrador puede registrar también las respuestas recibidas por WhatsApp u otros medios.</p></div><div className={'teams-contador '+(plazas&&totalElegibles<plazas?'faltan':'')}><strong>{totalElegibles}</strong><span>{plazas?'apuntados · '+plazas+' plazas previstas':'apuntados'}</span>{pendientes>0&&<small>{pendientes} pendientes</small>}</div></div>
 <div className="teams-convocatoria-tools"><input type="search" placeholder="Buscar jugador…" value={buscar} onChange={e=>setBuscar(e.target.value)}/><button className="boton boton-secundario" type="button" onClick={()=>{const n={...estados};jugadores.forEach(j=>n[j.id_jugador]='elegible');setEstados(n);setGuardado(false);setMensaje('')}}>Todos: Me apunto</button></div>
 {cargando?<div className="teams-vacio">Cargando catálogo…</div>:<div className="teams-jugadores teams-jugadores-estados">{filtrados.map(j=>{const estado=estados[j.id_jugador]||'';return <article key={j.id_jugador} className={'teams-jugador-estado '+(estado||'sin-respuesta')}><div className="teams-jugador-identidad"><span className="teams-avatar">{(j.alias||j.nombre_oficial||'?').trim().charAt(0).toUpperCase()}</span><span><b>{j.alias||j.nombre_oficial}</b>{j.alias&&j.nombre_oficial!==j.alias&&<small>{j.nombre_oficial}</small>}</span></div><div className="teams-estado-opciones">{OPCIONES.map(([v,t])=><button type="button" key={v} className={estado===v?'activo '+v:''} onClick={()=>cambiar(j.id_jugador,v)}>{t}</button>)}</div><small className="teams-origen">{origenes[j.id_jugador]==='web'?'Respondido en web':estado?'Marcado por administrador':'Sin respuesta'}</small></article>})}</div>}
 {mensaje&&<p className={mensaje.startsWith('Error:')?'teams-error':'teams-ok'}>{mensaje}</p>}<footer className="teams-convocatoria-acciones"><span>{plazas&&totalElegibles<plazas?'Faltan '+(plazas-totalElegibles)+' apuntados para cubrir las plazas previstas.':plazas&&totalElegibles>plazas?(totalElegibles-plazas)+' jugadores podrán quedar sin seleccionar o como reservas generales.':' '}</span><button type="button" className="boton boton-principal" disabled={guardando||cargando||guardado} onClick={guardar}>{guardando?'Guardando…':guardado?'Guardado ✓':'Guardar cambios'}</button></footer></section>
}