import { useMemo, useState } from 'react'
import { crearTeams } from '../teamsApi'

const PASOS = ['General','Formación','Participación','Parejas','Publicación','Revisión']
const inicial = { nombre:'',fecha_inicio:'',fecha_fin:'',modalidad:'mejor_de',numero_partidos:7,puntos_por_victoria:1,metodo_formacion:'manual',jugadores_por_equipo:8,reservas_por_equipo:0,tipo_draft:'alterno',computa_estadisticas:true,computa_ranking:false,computa_isp:false,repetir_jugadores:'si',max_partidos_jugador:'',repetir_pareja:false,todos_antes_repetir:false,sistema_eleccion_parejas:'secreto',primer_presentador:'sorteo',segundo_ve_pareja:false,plazo_presentar_horas:48,modo_publicacion:'inmediata',publicar_at:'',plazo_acordar_dias:3,plazo_jugar_dias:7,tratamiento_no_finalizado:'reanudar' }

export default function CrearTeams({ onCancelar, onCreado }) {
 const [paso,setPaso]=useState(0),[form,setForm]=useState(inicial),[error,setError]=useState(''),[guardando,setGuardando]=useState(false)
 const set=(k,v)=>setForm(a=>({...a,[k]:v}))
 const viabilidad=useMemo(()=>{const j=Number(form.jugadores_por_equipo)||0,p=Number(form.numero_partidos)||0;if(j<2)return 'Cada equipo necesita al menos 2 jugadores.';let max=Infinity;if(form.repetir_jugadores==='no')max=Math.floor(j/2);if(form.repetir_jugadores==='maximo'){const x=Number(form.max_partidos_jugador)||0;if(!x)return 'Indica el máximo de partidos por jugador.';max=Math.floor(j*x/2)}if(!form.repetir_pareja)max=Math.min(max,j*(j-1)/2);return p>max?`Con estas reglas solo son posibles ${max} partidos por equipo y has configurado ${p}. Aumenta jugadores, permite más repeticiones o reduce el número de partidos.`:''},[form.jugadores_por_equipo,form.numero_partidos,form.repetir_jugadores,form.max_partidos_jugador,form.repetir_pareja])
 const resumen=useMemo(()=>({formato:{numero_fijo:'Número fijo',mejor_de:'Al mejor de X',mejor_de_jugar_todos:'Al mejor de X · jugar todos',numero_fijo_desempate:'Número fijo + desempate'}[form.modalidad],formacion:{manual:'Manual',draft:'Draft de capitanes',sorteo:'Sorteo'}[form.metodo_formacion]}),[form])
 async function guardar(e){e.preventDefault();if(!form.nombre.trim())return setError('El nombre del Teams es obligatorio.');if(viabilidad)return setError(viabilidad);setGuardando(true);setError('');try{await crearTeams(form);await onCreado()}catch(e){setError(e.message)}finally{setGuardando(false)}}
 return <main className="teams-admin"><form className="teams-asistente" onSubmit={guardar}>
  <div className="teams-asistente-cab"><div><p className="etiqueta">NUEVO TEAMS</p><h2>{paso+1}. {PASOS[paso]}</h2></div><button type="button" className="boton boton-secundario" onClick={onCancelar}>Cerrar</button></div>
  {error&&<p className="teams-error">{error}</p>}<div className="teams-pasos">{PASOS.map((x,i)=><span key={x} className={i<=paso?'activo':''}>{i+1}</span>)}</div>
  {paso===0&&<div className="teams-campos"><label>Nombre<input value={form.nombre} onChange={e=>set('nombre',e.target.value)} placeholder="Teams Octubre 2026" required/></label><div className="teams-grid"><label>Fecha inicio<input type="date" value={form.fecha_inicio} onChange={e=>set('fecha_inicio',e.target.value)}/></label><label>Fecha fin<input type="date" value={form.fecha_fin} onChange={e=>set('fecha_fin',e.target.value)}/></label></div><label>Formato<select value={form.modalidad} onChange={e=>set('modalidad',e.target.value)}><option value="numero_fijo">Número fijo de partidos</option><option value="mejor_de">Al mejor de X</option><option value="mejor_de_jugar_todos">Al mejor de X, jugando todos</option><option value="numero_fijo_desempate">Número fijo + desempate</option></select></label><div className="teams-grid"><label>N.º partidos<input type="number" min="1" value={form.numero_partidos} onChange={e=>set('numero_partidos',e.target.value)}/></label><label>Puntos por victoria<input type="number" min="0" step=".5" value={form.puntos_por_victoria} onChange={e=>set('puntos_por_victoria',e.target.value)}/></label></div><div className="teams-checks"><label><input type="checkbox" checked={form.computa_estadisticas} onChange={e=>set('computa_estadisticas',e.target.checked)}/> Estadísticas Teams</label><label><input type="checkbox" checked={form.computa_ranking} onChange={e=>set('computa_ranking',e.target.checked)}/> Ranking</label><label><input type="checkbox" checked={form.computa_isp} onChange={e=>set('computa_isp',e.target.checked)}/> ISP</label></div></div>}
  {paso===1&&<div className="teams-campos"><label>Formación<select value={form.metodo_formacion} onChange={e=>set('metodo_formacion',e.target.value)}><option value="manual">Manual</option><option value="draft">Draft de capitanes</option><option value="sorteo">Sorteo</option></select></label><div className="teams-grid"><label>Jugadores por equipo<input type="number" min="1" value={form.jugadores_por_equipo} onChange={e=>set('jugadores_por_equipo',e.target.value)}/></label><label>Reservas por equipo<input type="number" min="0" value={form.reservas_por_equipo} onChange={e=>set('reservas_por_equipo',e.target.value)}/></label></div>{form.metodo_formacion==='draft'&&<label>Tipo de draft<select value={form.tipo_draft} onChange={e=>set('tipo_draft',e.target.value)}><option value="alterno">Alterno · A-B-A-B</option><option value="serpiente">Serpiente · A-B-B-A</option><option value="secreto_rondas">Secreto por rondas</option><option value="conjunto">Selección conjunta</option></select></label>}</div>}
  {paso===2&&<div className="teams-campos"><label>Repetir jugadores<select value={form.repetir_jugadores} onChange={e=>set('repetir_jugadores',e.target.value)}><option value="no">No</option><option value="si">Sí</option><option value="maximo">Sí, máximo X partidos</option></select></label>{form.repetir_jugadores==='maximo'&&<label>Máximo por jugador<input type="number" min="1" value={form.max_partidos_jugador} onChange={e=>set('max_partidos_jugador',e.target.value)}/></label>}<div className="teams-checks"><label><input type="checkbox" checked={form.repetir_pareja} onChange={e=>set('repetir_pareja',e.target.checked)}/> Permitir repetir pareja</label><label><input type="checkbox" checked={form.todos_antes_repetir} onChange={e=>set('todos_antes_repetir',e.target.checked)}/> Todos deben jugar antes de repetir</label></div></div>}
  {paso===3&&<div className="teams-campos"><label>Sistema de parejas<select value={form.sistema_eleccion_parejas} onChange={e=>set('sistema_eleccion_parejas',e.target.value)}><option value="secreto">Secreto / simultáneo</option><option value="alterno">Alterno</option><option value="ganador_primero">Ganador anterior presenta primero</option></select></label>{form.sistema_eleccion_parejas!=='secreto'&&<><label>Primer presentador<select value={form.primer_presentador} onChange={e=>set('primer_presentador',e.target.value)}><option value="sorteo">Sorteo</option><option value="equipo_a">Equipo A</option><option value="equipo_b">Equipo B</option></select></label><label className="teams-check"><input type="checkbox" checked={form.segundo_ve_pareja} onChange={e=>set('segundo_ve_pareja',e.target.checked)}/> El segundo capitán ve la primera pareja</label></>}<label>Plazo para presentar (horas)<input type="number" min="1" value={form.plazo_presentar_horas} onChange={e=>set('plazo_presentar_horas',e.target.value)}/></label></div>}
  {paso===4&&<div className="teams-campos"><label>Publicar parejas<select value={form.modo_publicacion} onChange={e=>set('modo_publicacion',e.target.value)}><option value="inmediata">Al confirmar ambos</option><option value="programada">Fecha/hora programada</option><option value="manual">Manual por administrador</option></select></label>{form.modo_publicacion==='programada'&&<label>Fecha/hora<input type="datetime-local" value={form.publicar_at} onChange={e=>set('publicar_at',e.target.value)}/></label>}<div className="teams-grid"><label>Plazo para acordar fecha (días)<input type="number" min="1" value={form.plazo_acordar_dias} onChange={e=>set('plazo_acordar_dias',e.target.value)}/></label><label>Plazo para jugar (días)<input type="number" min="1" value={form.plazo_jugar_dias} onChange={e=>set('plazo_jugar_dias',e.target.value)}/></label></div><label>Si no termina<select value={form.tratamiento_no_finalizado} onChange={e=>set('tratamiento_no_finalizado',e.target.value)}><option value="reanudar">Debe reanudarse</option><option value="administrador">Decide administrador</option></select></label></div>}
  {paso===5&&<div className="teams-resumen">{viabilidad&&<p className="teams-error">{viabilidad}</p>}<h3>{form.nombre||'Teams sin nombre'}</h3><p><b>Formato:</b> {resumen.formato} · {form.numero_partidos} partidos</p><p><b>Formación:</b> {resumen.formacion}{form.metodo_formacion==='draft'?' · '+form.tipo_draft:''}</p><p><b>Plantillas:</b> {form.jugadores_por_equipo} jugadores · {form.reservas_por_equipo} reservas/equipo</p><p><b>Parejas:</b> {form.sistema_eleccion_parejas} · plazo {form.plazo_presentar_horas} h</p><p><b>Computa:</b> Estadísticas {form.computa_estadisticas?'Sí':'No'} · Ranking {form.computa_ranking?'Sí':'No'} · ISP {form.computa_isp?'Sí':'No'}</p><div className="teams-aviso">Se creará en estado <b>Preparación</b>. Después configuraremos convocatoria, elegibles y capitanes.</div></div>}
  <footer className="teams-acciones">{paso>0?<button type="button" className="boton boton-secundario" onClick={()=>setPaso(p=>p-1)}>← Anterior</button>:<span/>}{paso<5?<button type="button" className="boton boton-principal" onClick={()=>{if(paso===0&&!form.nombre.trim()){setError('Escribe el nombre del Teams.');return}if((paso===1||paso===2)&&viabilidad){setError(viabilidad);return}setError('');setPaso(p=>p+1)}}>Siguiente →</button>:<button className="boton boton-principal" disabled={guardando}>{guardando?'Creando…':'Crear Teams'}</button>}</footer>
 </form></main>
}
