import { useEffect, useState } from 'react'
import { configurarEquiposTeams, obtenerDetalleTeams } from '../teamsApi'
export default function Equipos({teams}){
 const [detalle,setDetalle]=useState(null),[a,setA]=useState('Equipo A'),[b,setB]=useState('Equipo B'),[ca,setCa]=useState(''),[cb,setCb]=useState(''),[mensaje,setMensaje]=useState(''),[guardando,setGuardando]=useState(false),[guardado,setGuardado]=useState(false)
 useEffect(()=>{(async()=>{try{const d=await obtenerDetalleTeams(teams.id);setDetalle(d);const ea=(d.equipos||[]).find(x=>x.lado==='A'),eb=(d.equipos||[]).find(x=>x.lado==='B');if(ea){setA(ea.nombre||'Equipo A');setCa(ea.id_capitan||'')}if(eb){setB(eb.nombre||'Equipo B');setCb(eb.id_capitan||'')}setGuardado(Boolean(ea?.id_capitan&&eb?.id_capitan))}catch(e){setMensaje('Error: '+e.message)}})()},[teams.id])
 const elegibles=(detalle?.elegibles||[]).filter(x=>x.estado==='elegible')
 function editar(campo,valor){setGuardado(false);setMensaje('');campo(valor)}
 async function guardar(){if(!ca||!cb)return setMensaje('Error: Debes elegir los dos capitanes.');if(ca===cb)return setMensaje('Error: Los capitanes deben ser jugadores distintos.');setGuardando(true);setMensaje('');try{await configurarEquiposTeams(teams.id,a,ca,b,cb);setMensaje('Equipos y capitanes guardados correctamente.');setGuardado(true)}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 return <section className="teams-convocatoria"><div className="teams-seccion-cab"><div><p className="etiqueta">FORMACIÓN</p><h2>Equipos y capitanes</h2><p>Los capitanes deben estar entre los jugadores apuntados en la convocatoria.</p></div></div>
 <div className="teams-dos-equipos"><div className="teams-equipo-box equipo-a"><span className="teams-letra">A</span><label>Nombre del equipo<input value={a} onChange={e=>editar(setA,e.target.value)}/></label><label>Capitán<select value={ca} onChange={e=>editar(setCa,e.target.value)}><option value="">Seleccionar capitán…</option>{elegibles.filter(x=>x.id_jugador!==cb).map(x=><option key={x.id_jugador} value={x.id_jugador}>{x.alias||x.nombre}</option>)}</select></label></div>
 <div className="teams-versus">VS</div><div className="teams-equipo-box equipo-b"><span className="teams-letra">B</span><label>Nombre del equipo<input value={b} onChange={e=>editar(setB,e.target.value)}/></label><label>Capitán<select value={cb} onChange={e=>editar(setCb,e.target.value)}><option value="">Seleccionar capitán…</option>{elegibles.filter(x=>x.id_jugador!==ca).map(x=><option key={x.id_jugador} value={x.id_jugador}>{x.alias||x.nombre}</option>)}</select></label></div></div>
 <div className="teams-formacion-info"><b>Método de formación:</b> {teams.metodo_formacion==='draft'?'Draft de capitanes':teams.metodo_formacion==='sorteo'?'Sorteo':'Manual'}<span>Después de guardar los capitanes prepararemos la asignación del resto de jugadores.</span></div>
 {mensaje&&<p className={mensaje.startsWith('Error:')?'teams-error':'teams-ok'}>{mensaje}</p>}<footer className="teams-convocatoria-acciones"><span>{elegibles.length} jugadores apuntados disponibles</span><button type="button" className="boton boton-principal" onClick={guardar} disabled={guardando||!detalle||guardado}>{guardando?'Guardando…':guardado?'Guardado ✓':'Guardar cambios'}</button></footer></section>
}