import { useEffect, useState } from 'react'
import { configurarEquiposTeams, guardarFormacionManualTeams, obtenerDetalleTeams } from '../teamsApi'
export default function Equipos({teams}){
 const [detalle,setDetalle]=useState(null),[a,setA]=useState('Equipo A'),[b,setB]=useState('Equipo B'),[ca,setCa]=useState(''),[cb,setCb]=useState(''),[mensaje,setMensaje]=useState(''),[guardando,setGuardando]=useState(false),[guardado,setGuardado]=useState(false),[asignaciones,setAsignaciones]=useState({}),[plantillaGuardada,setPlantillaGuardada]=useState(false)
 useEffect(()=>{(async()=>{try{const d=await obtenerDetalleTeams(teams.id);setDetalle(d);const ea=(d.equipos||[]).find(x=>x.lado==='A'),eb=(d.equipos||[]).find(x=>x.lado==='B');if(ea){setA(ea.nombre||'Equipo A');setCa(ea.id_capitan||'')}if(eb){setB(eb.nombre||'Equipo B');setCb(eb.id_capitan||'')}setGuardado(Boolean(ea?.id_capitan&&eb?.id_capitan));const as={};for(const m of d.miembros||[])as[m.id_jugador]=(d.equipos||[]).find(e=>e.id===m.equipo_id)?.lado||'';setAsignaciones(as);setPlantillaGuardada((d.miembros||[]).length>0)}catch(e){setMensaje('Error: '+e.message)}})()},[teams.id])
 const elegibles=(detalle?.elegibles||[]).filter(x=>x.estado==='elegible')
 function editar(campo,valor){setGuardado(false);setMensaje('');campo(valor)}
 function asignar(id,lado){setAsignaciones(x=>({...x,[id]:lado}));setPlantillaGuardada(false);setMensaje('')}
 async function guardar(){if(!ca||!cb)return setMensaje('Error: Debes elegir los dos capitanes.');if(ca===cb)return setMensaje('Error: Los capitanes deben ser jugadores distintos.');setGuardando(true);setMensaje('');try{await configurarEquiposTeams(teams.id,a,ca,b,cb);setMensaje('Equipos y capitanes guardados correctamente.');setGuardado(true)}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 async function guardarPlantilla(){if(!ca||!cb)return setMensaje('Error: Guarda primero los capitanes.');const as={...asignaciones,[ca]:'A',[cb]:'B'};setGuardando(true);setMensaje('');try{await guardarFormacionManualTeams(teams.id,Object.entries(as).filter(([,lado])=>lado).map(([id_jugador,lado])=>({id_jugador,lado,es_reserva:false})));setAsignaciones(as);setPlantillaGuardada(true);setMensaje('Plantillas guardadas correctamente.')}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 const asignadosA=new Set([ca,...Object.entries(asignaciones).filter(([,x])=>x==='A').map(([id])=>id)]),asignadosB=new Set([cb,...Object.entries(asignaciones).filter(([,x])=>x==='B').map(([id])=>id)])
 return <section className="teams-convocatoria"><div className="teams-seccion-cab"><div><p className="etiqueta">FORMACIÓN</p><h2>Equipos y capitanes</h2><p>Los capitanes deben estar entre los jugadores apuntados en la convocatoria.</p></div></div>
 <div className="teams-dos-equipos"><div className="teams-equipo-box equipo-a"><span className="teams-letra">A</span><label>Nombre del equipo<input value={a} onChange={e=>editar(setA,e.target.value)}/></label><label>Capitán<select value={ca} onChange={e=>editar(setCa,e.target.value)}><option value="">Seleccionar capitán…</option>{elegibles.filter(x=>x.id_jugador!==cb).map(x=><option key={x.id_jugador} value={x.id_jugador}>{x.alias||x.nombre}</option>)}</select></label></div>
 <div className="teams-versus">VS</div><div className="teams-equipo-box equipo-b"><span className="teams-letra">B</span><label>Nombre del equipo<input value={b} onChange={e=>editar(setB,e.target.value)}/></label><label>Capitán<select value={cb} onChange={e=>editar(setCb,e.target.value)}><option value="">Seleccionar capitán…</option>{elegibles.filter(x=>x.id_jugador!==ca).map(x=><option key={x.id_jugador} value={x.id_jugador}>{x.alias||x.nombre}</option>)}</select></label></div></div>
 <div className="teams-formacion-info"><b>Método de formación:</b> {teams.metodo_formacion==='draft'?'Draft de capitanes':teams.metodo_formacion==='sorteo'?'Sorteo':'Manual'}</div>
 {teams.metodo_formacion==='manual'&&ca&&cb&&<div className="teams-reparto"><div className="teams-reparto-cab"><div><h3>Reparto manual</h3><p>Asigna cada jugador a uno de los dos equipos. Los capitanes quedan fijados automáticamente.</p></div><span>{asignadosA.size} / {teams.jugadores_por_equipo||'—'} · {asignadosB.size} / {teams.jugadores_por_equipo||'—'}</span></div><div className="teams-reparto-lista">{elegibles.map(j=>{const id=j.id_jugador,esA=id===ca,esB=id===cb,lado=esA?'A':esB?'B':asignaciones[id]||'';return <div className="teams-reparto-jugador" key={id}><b>{j.alias||j.nombre}</b><div><button type="button" className={lado==='A'?'activo':''} disabled={esB} onClick={()=>!esA&&asignar(id,lado==='A'?'':'A')}>{a}{esA?' · Capitán':''}</button><button type="button" className={lado==='B'?'activo':''} disabled={esA} onClick={()=>!esB&&asignar(id,lado==='B'?'':'B')}>{b}{esB?' · Capitán':''}</button></div></div>})}</div><div className="teams-reparto-acciones"><span>{elegibles.length-asignadosA.size-asignadosB.size} sin asignar</span><button type="button" className="boton boton-principal" disabled={guardando||plantillaGuardada} onClick={guardarPlantilla}>{guardando?'Guardando…':plantillaGuardada?'Plantillas guardadas ✓':'Guardar plantillas'}</button></div></div>}
 {mensaje&&<p className={mensaje.startsWith('Error:')?'teams-error':'teams-ok'}>{mensaje}</p>}<footer className="teams-convocatoria-acciones"><span>{elegibles.length} jugadores apuntados disponibles</span><button type="button" className="boton boton-principal" onClick={guardar} disabled={guardando||!detalle||guardado}>{guardando?'Guardando…':guardado?'Guardado ✓':'Guardar cambios'}</button></footer></section>
}