import { useEffect, useState } from 'react'
import { obtenerDetalleTeams, resolverIncidenciaTeams } from '../teamsApi'

export default function Incidencias({teams,onCambio}){
 const [d,setD]=useState(null),[nota,setNota]=useState({}),[mensaje,setMensaje]=useState(''),[guardando,setGuardando]=useState(false),[abierta,setAbierta]=useState(null)
 async function cargar(){try{setD(await obtenerDetalleTeams(teams.id))}catch(e){setMensaje('Error: '+e.message)}}
 useEffect(()=>{void cargar()},[teams.id])
 if(!d)return <section className="teams-convocatoria"><div className="teams-vacio">Cargando incidencias…</div></section>
 const incidencias=d.incidencias||[], pendientes=incidencias.filter(i=>i.estado==='pendiente'), resueltas=incidencias.filter(i=>i.estado!=='pendiente')
 function partido(i){return (d.partidos||[]).find(p=>p.id===i.partido_id)}
 function sets(pid){return (d.sets||[]).filter(s=>s.partido_id===pid).sort((a,b)=>a.numero-b.numero)}
 async function resolver(i,accion){setGuardando(true);setMensaje('');try{await resolverIncidenciaTeams(i.id,accion,nota[i.id]);setMensaje(accion==='validar'?'Resultado validado y punto adjudicado.':accion==='corregir'?'Partido devuelto para corregir el resultado.':accion==='reconfirmar'?'Resultado enviado de nuevo a confirmación.':'Partido anulado.');await cargar();onCambio?.()}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 return <section className="teams-convocatoria"><div className="teams-seccion-cab"><div><p className="etiqueta">INCIDENCIAS</p><h2>Incidencias del Teams</h2><p>Revisa y resuelve resultados impugnados y otras situaciones excepcionales.</p></div><div className="teams-contador"><strong>{pendientes.length}</strong><span>pendientes</span></div></div>
 {mensaje&&<p className={mensaje.startsWith('Error:')?'teams-error':'teams-ok'}>{mensaje}</p>}
 {pendientes.length===0?<div className="teams-vacio"><strong>No hay incidencias pendientes</strong><span>Las incidencias resueltas quedan guardadas en el histórico.</span></div>:<div className="teams-incidencias-lista">{pendientes.map(i=>{const p=partido(i);return <article className="teams-incidencia-card" key={i.id}><header><div><span>⚠ INCIDENCIA PENDIENTE</span><h3>Partido {p?.numero??'—'}</h3></div><b>{i.tipo==='resultado_impugnado'?'Resultado impugnado':i.tipo.replaceAll('_',' ')}</b></header><div className="teams-incidencia-marcador">{sets(i.partido_id).map(s=><span key={s.numero}>Set {s.numero}: <strong>{s.puntos_a}–{s.puntos_b}</strong>{s.tiebreak_a!=null&&<small> TB {s.tiebreak_a}–{s.tiebreak_b}</small>}</span>)}</div><div className="teams-incidencia-motivo"><b>Motivo</b><p>{i.detalle||'Sin detalle'}</p></div><label className="teams-incidencia-nota">Nota de resolución <small>(opcional)</small><textarea rows="3" placeholder="Añade una explicación para dejar constancia…" value={nota[i.id]||''} onChange={e=>setNota(x=>({...x,[i.id]:e.target.value}))}/></label><div className="teams-incidencia-acciones"><button className="boton boton-principal" disabled={guardando} onClick={()=>resolver(i,'validar')}>Validar resultado</button><button className="boton boton-secundario" disabled={guardando} onClick={()=>resolver(i,'corregir')}>Corregir resultado</button><button className="boton boton-secundario" disabled={guardando} onClick={()=>resolver(i,'reconfirmar')}>Nueva confirmación</button><button className="boton boton-peligro" disabled={guardando} onClick={()=>resolver(i,'anular')}>Anular partido</button></div></article>})}</div>}
 {resueltas.length>0&&<div className="teams-incidencias-historico"><h3>Histórico de incidencias</h3>{resueltas.map(i=>{const abiertaAhora=abierta===i.id;return <div className="teams-incidencia-historica" key={i.id}><div className="teams-incidencia-historica-resumen"><div><b>Partido {partido(i)?.numero??'—'} · {i.tipo==='resultado_impugnado'?'resultado impugnado':i.tipo.replaceAll('_',' ')}</b><small>{i.resolucion||'Resuelta'}</small></div><span>✓ Resuelta</span><button type="button" className="boton boton-secundario teams-ver-incidencia" onClick={()=>setAbierta(abiertaAhora?null:i.id)}>{abiertaAhora?'Ocultar detalle':'Ver detalle'}</button></div>{abiertaAhora&&<div className="teams-incidencia-historica-detalle"><div><b>Incidencia</b><p>{i.detalle||'Sin detalle registrado'}</p></div><div><b>Resolución</b><p>{i.resolucion||'Resuelta'}</p></div></div>}</div>})}</div>}</section>
}