import { useEffect, useRef, useState } from 'react'
import { confirmarHorarioTeams, eliminarProgramacionTeams, guardarAlineacionTeams, modificarProgramacionTeams, obtenerDetalleTeams, proponerHorarioTeams, revelarAlineacionesTeams, actualizarPistaTeams, confirmarResultadoTeams, guardarResultadoTeams, impugnarResultadoTeams } from '../teamsApi'
function CampoFecha({value,onChange}){const ref=useRef(null);function abrir(){const el=ref.current;if(!el)return;try{el.showPicker?.()}catch{} el.focus()}return <div className="teams-fecha-control"><input ref={ref} type="datetime-local" value={value} onChange={onChange}/><button type="button" className="teams-calendario-btn" aria-label="Abrir calendario" title="Abrir calendario" onClick={abrir}>▣</button></div>}
export default function Partidos({teams,onCambio}){
 const [d,setD]=useState(null),[sel,setSel]=useState({}),[agenda,setAgenda]=useState({}),[mensaje,setMensaje]=useState(''),[guardando,setGuardando]=useState(false)
 async function cargar(){try{setD(await obtenerDetalleTeams(teams.id))}catch(e){setMensaje('Error: '+e.message)}}
 useEffect(()=>{void cargar()},[teams.id])
 if(!d)return <section className="teams-convocatoria"><div className="teams-vacio">Cargando partidos…</div></section>
 const eq=d.equipos||[],miembros=d.miembros||[],als=d.alineaciones||[],partidos=d.partidos||[],propuestas=d.propuestas||[]
 function jugadoresEquipo(eid){return miembros.filter(m=>m.equipo_id===eid&&!m.es_reserva&&m.disponible!==false)}
 function pareja(pid,eid){return als.filter(a=>a.partido_id===pid&&a.equipo_id===eid).sort((a,b)=>a.orden-b.orden)}
 function valor(pid,eid,n){return sel[pid+'-'+eid+'-'+n]??pareja(pid,eid)[n-1]?.id_jugador??''}
 function setv(pid,eid,n,v){setSel(x=>({...x,[pid+'-'+eid+'-'+n]:v}));setMensaje('')}
 function ag(pid,k){return agenda[pid+'-'+k]??''} function sag(pid,k,v){setAgenda(x=>({...x,[pid+'-'+k]:v}));setMensaje('')}
 function props(pid){return propuestas.filter(x=>x.partido_id===pid)}
 function setsPartido(pid){return (d.sets||[]).filter(x=>x.partido_id===pid).sort((a,b)=>a.numero-b.numero)}
 function fecha(v){return new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
 async function guardar(p,e){const j1=valor(p.id,e.id,1),j2=valor(p.id,e.id,2);if(!j1||!j2)return setMensaje('Error: Selecciona los dos jugadores de '+e.nombre+'.');setGuardando(true);try{await guardarAlineacionTeams(p.id,e.id,j1,j2);setMensaje('Pareja de '+e.nombre+' guardada correctamente.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function revelar(p){setGuardando(true);try{await revelarAlineacionesTeams(p.id);setMensaje('Parejas reveladas. Ya podéis concertar el partido.');await cargar();onCambio?.()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function proponer(p){const fh=ag(p.id,'fecha');if(!fh)return setMensaje('Error: Indica una fecha y hora.');setGuardando(true);try{await proponerHorarioTeams(p.id,new Date(fh).toISOString(),ag(p.id,'pista'));sag(p.id,'fecha','');sag(p.id,'pista','');setMensaje('Propuesta añadida. Puedes añadir más alternativas.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function confirmar(p,pr){setGuardando(true);try{await confirmarHorarioTeams(p.id,pr.id,ag(p.id,'pistaConfirmada'));setMensaje('Fecha confirmada. Partido programado.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function modificarProgramacion(p){const fh=ag(p.id,'editarFecha');if(!fh)return setMensaje('Error: Indica la nueva fecha y hora.');setGuardando(true);try{await modificarProgramacionTeams(p.id,new Date(fh).toISOString(),ag(p.id,'editarPista'));setMensaje('Programación modificada.');sag(p.id,'editando','');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function eliminarProgramacion(p){setGuardando(true);try{await eliminarProgramacionTeams(p.id);setMensaje('Fecha eliminada. El partido vuelve a estar pendiente de concertar.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function pista(p){setGuardando(true);try{await actualizarPistaTeams(p.id,ag(p.id,'pistaFinal'));setMensaje('Club / pista actualizado.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function guardarResultado(p){const fin=ag(p.id,'fin')||'normal',sets=[1,2,3].map(n=>({numero:n,a:Number(ag(p.id,'s'+n+'a')||0),b:Number(ag(p.id,'s'+n+'b')||0),tiebreak_a:ag(p.id,'tb'+n+'a')===''||ag(p.id,'tb'+n+'a')==null?null:Number(ag(p.id,'tb'+n+'a')),tiebreak_b:ag(p.id,'tb'+n+'b')===''||ag(p.id,'tb'+n+'b')==null?null:Number(ag(p.id,'tb'+n+'b'))})).filter(x=>x.a||x.b||x.tiebreak_a!=null||x.tiebreak_b!=null);const ganador=ag(p.id,'ganador')||null;setGuardando(true);try{await guardarResultadoTeams(p.id,sets,fin,ganador,Number(ag(p.id,'duracion'))||null,ag(p.id,'obs'));setMensaje(fin==='suspendido'||fin==='no_finalizado'?'Partido enviado a incidencias sin otorgar punto.':'Resultado guardado. Pendiente de confirmación rival.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function confirmarResultado(p){setGuardando(true);try{await confirmarResultadoTeams(p.id);setMensaje('Resultado confirmado y punto adjudicado.');await cargar();onCambio?.()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 async function impugnar(p){const motivo=ag(p.id,'motivo');if(!motivo)return setMensaje('Error: Indica el motivo de la impugnación.');setGuardando(true);try{await impugnarResultadoTeams(p.id,motivo);setMensaje('Resultado impugnado. Se ha creado una incidencia.');await cargar()}catch(x){setMensaje('Error: '+x.message)}finally{setGuardando(false)}}
 const estados={pendiente_alineaciones:'Pendiente de parejas',alineaciones_cerradas:'Parejas cerradas',revelado:'Parejas reveladas',concertando:'Concertando fecha',programado:'Programado',pendiente_resultado:'Pendiente de resultado',pendiente_confirmacion:'Pendiente de confirmación',finalizado:'Finalizado',suspendido:'Suspendido',incidencia:'Incidencia',anulado:'Anulado'}
 return <section className="teams-convocatoria"><div className="teams-seccion-cab"><div><p className="etiqueta">PARTIDOS</p><h2>Partidos del Teams</h2><p>Gestiona las parejas, fecha y avance de cada enfrentamiento.</p></div><div className="teams-contador"><strong>{partidos.length}</strong><span>partidos creados</span></div></div>
 {mensaje&&<p className={mensaje.startsWith('Error:')?'teams-error':'teams-ok'}>{mensaje}</p>}
 <div className="teams-partidos-lista">{partidos.map(p=><article className="teams-partido-card" key={p.id}><header><div><span className="teams-partido-num">PARTIDO {p.numero}</span><h3>{eq[0]?.nombre||'Equipo A'} <i>vs</i> {eq[1]?.nombre||'Equipo B'}</h3></div><span className={'teams-partido-estado estado-'+p.estado}>{estados[p.estado]||p.estado}</span></header>
 <div className="teams-parejas">{eq.map(e=>{const par=pareja(p.id,e.id),bloqueado=!['pendiente_alineaciones','alineaciones_cerradas'].includes(p.estado);return <div className="teams-pareja-box" key={e.id}><div className="teams-pareja-titulo"><b>{e.nombre}</b>{p.presenta_primero_equipo_id===e.id&&<small>Presenta primero</small>}</div>{bloqueado?<div className="teams-pareja-revelada">{par.length?par.map(x=><span key={x.id_jugador}>{x.alias||x.nombre}</span>):<em>Sin pareja</em>}</div>:<><select value={valor(p.id,e.id,1)} onChange={x=>setv(p.id,e.id,1,x.target.value)}><option value="">Jugador 1…</option>{jugadoresEquipo(e.id).filter(j=>j.id_jugador!==valor(p.id,e.id,2)).map(j=><option key={j.id_jugador} value={j.id_jugador}>{j.alias||j.nombre}</option>)}</select><select value={valor(p.id,e.id,2)} onChange={x=>setv(p.id,e.id,2,x.target.value)}><option value="">Jugador 2…</option>{jugadoresEquipo(e.id).filter(j=>j.id_jugador!==valor(p.id,e.id,1)).map(j=><option key={j.id_jugador} value={j.id_jugador}>{j.alias||j.nombre}</option>)}</select><button type="button" className="boton boton-secundario" disabled={guardando} onClick={()=>guardar(p,e)}>{par.length===2?'Modificar pareja':'Guardar pareja'}</button></>}</div>})}</div>
 {p.estado==='alineaciones_cerradas'&&<footer className="teams-partido-acciones"><span>✓ Las dos parejas están presentadas.</span><button type="button" className="boton boton-principal" disabled={guardando} onClick={()=>revelar(p)}>Revelar parejas</button></footer>}
 {['revelado','concertando'].includes(p.estado)&&<div className="teams-concertar"><div className="teams-concertar-titulo"><div><b>Concertar partido</b><small>Propón una o varias alternativas. Confirma una cuando exista acuerdo.</small></div></div><div className="teams-propuesta-form"><label>Fecha y hora<CampoFecha value={ag(p.id,'fecha')} onChange={e=>sag(p.id,'fecha',e.target.value)}/></label><label>Club / pista <small>(opcional)</small><input placeholder="Ej. Máis que Auga · Pista 3" value={ag(p.id,'pista')} onChange={e=>sag(p.id,'pista',e.target.value)}/></label><button className="boton boton-secundario" disabled={guardando} onClick={()=>proponer(p)}>+ Añadir propuesta</button></div>{props(p.id).length>0&&<div className="teams-propuestas">{props(p.id).map(pr=><div className={'teams-propuesta '+pr.estado} key={pr.id}><div><b>{fecha(pr.fecha_hora)}</b><small>{pr.pista||'Club / pista pendiente'}</small></div><span>{pr.estado==='aceptada'?'✓ Aceptada':pr.estado==='rechazada'?'Descartada':'Propuesta'}</span>{pr.estado==='propuesta'&&<button className="boton boton-principal" disabled={guardando} onClick={()=>confirmar(p,pr)}>Confirmar fecha</button>}</div>)}</div>}</div>}
 {p.estado==='programado'&&<div className="teams-programado-wrap"><div className="teams-programado"><div><span>FECHA CONFIRMADA</span><b>{fecha(p.fecha_hora)}</b><small>{p.pista||'Club / pista sin indicar'}</small></div><div className="teams-programado-botones"><button className="boton boton-secundario" onClick={()=>{sag(p.id,'editando','si');const z=new Date(p.fecha_hora);z.setMinutes(z.getMinutes()-z.getTimezoneOffset());sag(p.id,'editarFecha',z.toISOString().slice(0,16));sag(p.id,'editarPista',p.pista||'')}}>Modificar</button><button className="boton boton-peligro" disabled={guardando} onClick={()=>eliminarProgramacion(p)}>Eliminar fecha</button></div></div>{ag(p.id,'editando')&&<div className="teams-editar-programacion"><label>Fecha y hora<CampoFecha value={ag(p.id,'editarFecha')} onChange={e=>sag(p.id,'editarFecha',e.target.value)}/></label><label>Club / pista <small>(opcional)</small><input placeholder="Puedes dejarlo vacío" value={ag(p.id,'editarPista')} onChange={e=>sag(p.id,'editarPista',e.target.value)}/></label><div><button className="boton boton-secundario" onClick={()=>sag(p.id,'editando','')}>Cancelar</button><button className="boton boton-principal" disabled={guardando} onClick={()=>modificarProgramacion(p)}>Guardar cambios</button></div></div>}{!p.pista&&!ag(p.id,'editando')&&<div className="teams-pista-opcional"><span>El club y la pista son opcionales.</span><input placeholder="Añadir club / pista si quieres" value={ag(p.id,'pistaFinal')} onChange={e=>sag(p.id,'pistaFinal',e.target.value)}/><button className="boton boton-secundario" disabled={guardando||!ag(p.id,'pistaFinal')} onClick={()=>pista(p)}>Añadir</button></div>}</div>}
 {p.estado==='programado'&&<div className="teams-resultado"><div className="teams-resultado-cab"><div><b>Introducir resultado</b><small>El resultado quedará pendiente de confirmación del rival.</small></div><select value={ag(p.id,'fin')||'normal'} onChange={e=>sag(p.id,'fin',e.target.value)}><option value="normal">Partido finalizado</option><option value="wo">W.O.</option><option value="retirada">Retirada</option><option value="suspendido">Suspendido</option><option value="no_finalizado">No finalizado</option></select></div>{(ag(p.id,'fin')||'normal')!=='wo'&&<div className="teams-sets-editor"><span></span><b>{eq[0]?.nombre}</b><b>{eq[1]?.nombre}</b>{[1,2,3].map(n=><div className="teams-set-fila" key={n}><span>Set {n}</span><input type="number" min="0" value={ag(p.id,'s'+n+'a')} onChange={e=>sag(p.id,'s'+n+'a',e.target.value)}/><input type="number" min="0" value={ag(p.id,'s'+n+'b')} onChange={e=>sag(p.id,'s'+n+'b',e.target.value)}/><div className="teams-tiebreak"><small>Tie-break (opcional)</small><input type="number" min="0" placeholder="—" value={ag(p.id,'tb'+n+'a')} onChange={e=>sag(p.id,'tb'+n+'a',e.target.value)}/><span>–</span><input type="number" min="0" placeholder="—" value={ag(p.id,'tb'+n+'b')} onChange={e=>sag(p.id,'tb'+n+'b',e.target.value)}/></div></div>)}</div>}{['wo','retirada'].includes(ag(p.id,'fin'))&&<label className="teams-ganador-especial">Equipo ganador<select value={ag(p.id,'ganador')} onChange={e=>sag(p.id,'ganador',e.target.value)}><option value="">Seleccionar…</option>{eq.map(e=><option value={e.id} key={e.id}>{e.nombre}</option>)}</select></label>}<div className="teams-resultado-extra"><label>Duración <small>(min, opcional)</small><input type="number" min="1" value={ag(p.id,'duracion')} onChange={e=>sag(p.id,'duracion',e.target.value)}/></label><label>Observaciones <small>(opcional)</small><input value={ag(p.id,'obs')} onChange={e=>sag(p.id,'obs',e.target.value)}/></label><button className="boton boton-principal" disabled={guardando} onClick={()=>guardarResultado(p)}>Guardar resultado</button></div></div>}
{p.estado==='pendiente_confirmacion'&&<div className="teams-confirmar-resultado"><div><span>RESULTADO PENDIENTE DE CONFIRMACIÓN</span><b>{p.finalizacion==='normal'?'Resultado del partido':p.finalizacion?.toUpperCase()}</b><div className="teams-marcador-sets">{setsPartido(p.id).map(x=><span key={x.numero}>Set {x.numero}: <strong>{x.puntos_a}–{x.puntos_b}</strong>{x.tiebreak_a!=null&&<small> TB {x.tiebreak_a}–{x.tiebreak_b}</small>}</span>)}</div></div><div className="teams-confirmacion-acciones"><button className="boton boton-principal" disabled={guardando} onClick={()=>confirmarResultado(p)}>Confirmar resultado</button><input placeholder="Motivo si no es correcto" value={ag(p.id,'motivo')} onChange={e=>sag(p.id,'motivo',e.target.value)}/><button className="boton boton-peligro" disabled={guardando} onClick={()=>impugnar(p)}>Impugnar</button></div></div>}
{p.estado==='finalizado'&&<div className="teams-resultado-oficial"><span>✓ RESULTADO OFICIAL</span><div>{setsPartido(p.id).map(x=><b key={x.numero}>{x.puntos_a}–{x.puntos_b}{x.tiebreak_a!=null&&<small> ({x.tiebreak_a}–{x.tiebreak_b})</small>}</b>)}</div></div>}
</article>)}</div></section>
}