import { useEffect, useState } from 'react'
import { guardarReglasTeams, marcarReglasRevisadasTeams, obtenerDetalleTeams } from '../teamsApi'
export default function Reglas({teams,onCambio}){
 const [f,setF]=useState(null),[guardado,setGuardado]=useState(true),[revisadas,setRevisadas]=useState(false),[guardando,setGuardando]=useState(false),[mensaje,setMensaje]=useState('')
 useEffect(()=>{(async()=>{try{const d=await obtenerDetalleTeams(teams.id),t=d.teams;setF({...t,...(t.configuracion||{})});setRevisadas(Boolean(t.reglas_revisadas))}catch(e){setMensaje('Error: '+e.message)}})()},[teams.id])
 function set(k,v){setF(x=>({...x,[k]:v}));setGuardado(false);setRevisadas(false);setMensaje('')}
 async function guardar(){setGuardando(true);setMensaje('');try{await guardarReglasTeams(teams.id,f);setGuardado(true);setMensaje('Reglas guardadas correctamente.')}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 async function revisar(){if(!guardado)return setMensaje('Error: Guarda primero los cambios.');setGuardando(true);try{await marcarReglasRevisadasTeams(teams.id,true);setRevisadas(true);setMensaje('Reglas revisadas ✓');onCambio?.()}catch(e){setMensaje('Error: '+e.message)}finally{setGuardando(false)}}
 if(!f)return <section className="teams-convocatoria"><div className="teams-vacio">Cargando reglas…</div></section>
 return <section className="teams-convocatoria"><div className="teams-seccion-cab"><div><p className="etiqueta">REGLAS</p><h2>Configuración de los partidos</h2><p>Revisa las reglas antes de iniciar el Teams. Mientras no haya comenzado puedes modificarlas.</p></div>{revisadas&&<span className="teams-reglas-ok">✓ Revisadas</span>}</div>
 <div className="teams-reglas-grid">
 <div className="teams-regla-bloque"><h3>Serie</h3><label>Formato<select value={f.modalidad} onChange={e=>set('modalidad',e.target.value)}><option value="numero_fijo">Número fijo</option><option value="mejor_de">Al mejor de X</option><option value="mejor_de_jugar_todos">Al mejor de X, jugar todos</option><option value="numero_fijo_desempate">Número fijo + desempate</option></select></label><label>N.º de partidos<input type="number" min="1" value={f.numero_partidos} onChange={e=>set('numero_partidos',Number(e.target.value))}/></label><label>Puntos por victoria<input type="number" min="0" step=".5" value={f.puntos_por_victoria} onChange={e=>set('puntos_por_victoria',Number(e.target.value))}/></label></div>
 <div className="teams-regla-bloque"><h3>Participación</h3><label>Repetir jugadores<select value={f.repetir_jugadores} onChange={e=>set('repetir_jugadores',e.target.value)}><option value="no">No</option><option value="si">Sí</option><option value="maximo">Sí, máximo X</option></select></label>{f.repetir_jugadores==='maximo'&&<label>Máximo partidos/jugador<input type="number" min="1" value={f.max_partidos_jugador||''} onChange={e=>set('max_partidos_jugador',Number(e.target.value)||null)}/></label>}<label className="teams-check"><input type="checkbox" checked={!!f.repetir_pareja} onChange={e=>set('repetir_pareja',e.target.checked)}/> Permitir repetir pareja</label><label className="teams-check"><input type="checkbox" checked={!!f.todos_antes_repetir} onChange={e=>set('todos_antes_repetir',e.target.checked)}/> Todos juegan antes de repetir</label></div>
 <div className="teams-regla-bloque"><h3>Elección de parejas</h3><label>Sistema<select value={f.sistema_eleccion_parejas} onChange={e=>set('sistema_eleccion_parejas',e.target.value)}><option value="secreto">Secreto / simultáneo</option><option value="alterno">Alterno</option><option value="ganador_primero">Ganador anterior primero</option></select></label>{f.sistema_eleccion_parejas!=='secreto'&&<><label>Primer presentador<select value={f.primer_presentador} onChange={e=>set('primer_presentador',e.target.value)}><option value="sorteo">Sorteo</option><option value="equipo_a">Equipo A</option><option value="equipo_b">Equipo B</option></select></label><label className="teams-check"><input type="checkbox" checked={!!f.segundo_ve_pareja} onChange={e=>set('segundo_ve_pareja',e.target.checked)}/> El segundo ve la primera pareja</label></>}<label>Plazo para presentar (h)<input type="number" min="1" value={f.plazo_presentar_horas||''} onChange={e=>set('plazo_presentar_horas',Number(e.target.value)||null)}/></label></div>
 <div className="teams-regla-bloque"><h3>Publicación y plazos</h3><label>Publicar parejas<select value={f.modo_publicacion} onChange={e=>set('modo_publicacion',e.target.value)}><option value="inmediata">Al confirmar ambos</option><option value="programada">Programada</option><option value="manual">Manual administrador</option></select></label><label>Plazo para acordar (días)<input type="number" min="1" value={f.plazo_acordar_dias||''} onChange={e=>set('plazo_acordar_dias',Number(e.target.value)||null)}/></label><label>Plazo para jugar (días)<input type="number" min="1" value={f.plazo_jugar_dias||''} onChange={e=>set('plazo_jugar_dias',Number(e.target.value)||null)}/></label><label>Partido no finalizado<select value={f.tratamiento_no_finalizado} onChange={e=>set('tratamiento_no_finalizado',e.target.value)}><option value="reanudar">Debe reanudarse</option><option value="administrador">Decide administrador</option></select></label></div>
 </div>
 {mensaje&&<p className={mensaje.startsWith('Error:')?'teams-error':'teams-ok'}>{mensaje}</p>}<footer className="teams-reglas-acciones"><button type="button" className="boton boton-secundario" disabled={guardando||guardado} onClick={guardar}>{guardando?'Guardando…':guardado?'Guardado ✓':'Guardar cambios'}</button><button type="button" className="boton boton-principal" disabled={guardando||!guardado||revisadas} onClick={revisar}>{revisadas?'Reglas revisadas ✓':'Confirmar reglas revisadas'}</button></footer>
 </section>
}