import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const norm=(s:string)=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase();
const rad=(x:number)=>x*Math.PI/180;
const km=(a:any,b:any)=>{const R=6371,d1=rad(Number(b.lat)-Number(a.lat)),d2=rad(Number(b.lon)-Number(a.lon));const q=Math.sin(d1/2)**2+Math.cos(rad(Number(a.lat)))*Math.cos(rad(Number(b.lat)))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const val=(ms:any[],keys:string[])=>{const ks=keys.map(x=>x.toUpperCase());for(const q of (ms||[])){const code=String(q.codigoParametro??q.codigo??q.parametro??q.nomeParametro??q.nome??"").toUpperCase();const raw=q.valor??q.valorMedida??q.value??q.dato;const n=Number(String(raw??"").replace(",", "."));if(ks.includes(code)&&Number.isFinite(n))return {v:n,u:String(q.unidade??q.unidad??q.unit??"")};}return null};
const madrid=(d:Date)=>new Intl.DateTimeFormat("es-ES",{timeZone:"Europe/Madrid",hour:"2-digit",minute:"2-digit",hour12:false}).format(d);
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{
 const b=await req.json();const j=await fetch("https://servizos.meteogalicia.gal/mgrss/observacion/listaEstacionsMeteo.action").then(r=>r.json());const lista=j.listaEstacionsMeteo||[];
 if(b.accion==="estaciones"){const loc=norm(b.localidad);const propias=lista.filter((e:any)=>norm(e.concello)===loc);let out=[...propias];if(propias.length){const centro={lat:propias.reduce((s:any,x:any)=>s+Number(x.lat),0)/propias.length,lon:propias.reduce((s:any,x:any)=>s+Number(x.lon),0)/propias.length};out=[...lista].sort((a:any,z:any)=>km(centro,a)-km(centro,z)).slice(0,12).map((x:any)=>({...x,distancia_km:Math.round(km(centro,x)*10)/10}))}return new Response(JSON.stringify({ok:true,estaciones:out.map((e:any)=>({id:e.idEstacion,nombre:e.estacion,concello:e.concello,lat:e.lat,lon:e.lon,altitude:e.altitude,distancia_km:e.distancia_km??null})),nota:"El listado oficial actual solo incluye estaciones activas."}),{headers:H})}
 const {localidad,fecha,horaInicio,horaFin,idEstacion}=b;let est=idEstacion?lista.find((e:any)=>String(e.idEstacion)===String(idEstacion)):null;if(!est&&localidad)est=lista.find((e:any)=>norm(e.concello)===norm(localidad));if(!est)throw new Error("No encontré una estación activa.");
 if(!horaInicio||!horaFin)throw new Error("Indica hora de inicio y hora de fin para obtener datos del campeonato.");
 const u=new URL("https://servizos.meteogalicia.gal/mgrss/observacion/ultimosHorariosEstacions.action");u.searchParams.set("numHoras","72");u.searchParams.set("idEst",String(est.idEstacion));const hj=await fetch(u).then(r=>r.json());const he=(hj.listHorarios||[]).find((x:any)=>String(x.idEstacion)===String(est.idEstacion));const inst=he?.listaInstantes||[];
 const localKey=(d:Date)=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Madrid",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(d).replace(" ","T");
 const ini=fecha+"T"+horaInicio, fin=fecha+"T"+horaFin;const rango=inst.filter((x:any)=>{const k=localKey(new Date(x.instanteLecturaUTC));return k>=ini&&k<=fin});
 
 const temps:any[]=[];for(const x of rango){const ms=x.listaMedidas||[];const q=val(ms,["TA_AVG","TA"]);if(q)temps.push({v:q.v,d:new Date(x.instanteLecturaUTC)});}if(!temps.length){for(const x of rango){const ms=x.listaMedidas||[];const a=val(ms,["TA_MIN"]),z=val(ms,["TA_MAX"]);if(a&&z)temps.push({v:(a.v+z.v)/2,d:new Date(x.instanteLecturaUTC)});else if(a)temps.push({v:a.v,d:new Date(x.instanteLecturaUTC)});else if(z)temps.push({v:z.v,d:new Date(x.instanteLecturaUTC)});}}if(!temps.length){
  const du=new URL("https://servizos.meteogalicia.gal/mgrss/observacion/datosDiariosEstacionsMeteo.action");
  du.searchParams.set("idEst",String(est.idEstacion));const partesFecha=fecha.split("-");const fechaDiaria=partesFecha[2]+"/"+partesFecha[1]+"/"+partesFecha[0];du.searchParams.set("dataIni",fechaDiaria);du.searchParams.set("dataFin",fechaDiaria);
  const dj=await fetch(du).then(r=>r.json());const candidatos=[...(dj.listaEstacions||[]),...(dj.listaEstacionsMeteo||[]),...((dj.listDatosDiarios||[]).flatMap((x:any)=>x.listaEstacions||[]))];const de=candidatos.find((x:any)=>String(x.idEstacion)===String(est.idEstacion))||candidatos[0];
  const dm=de?.listaMedidas||de?.medidas||de?.listaDatos||[];const dmin=val(dm,["TA_MIN"]),dmax=val(dm,["TA_MAX"]),davg=val(dm,["TA_AVG"]),dpp=val(dm,["PP_SUM"]),dwa=val(dm,["VV_AVG"]),dwm=val(dm,["VV_MAX"]);
  const hmin=(dm.find((q:any)=>String(q.codigoParametro||"").toUpperCase()==="TA_MIN")?.hora||dm.find((q:any)=>String(q.codigoParametro||"").toUpperCase()==="TA_MIN")?.instante||null);
  const hmax=(dm.find((q:any)=>String(q.codigoParametro||"").toUpperCase()==="TA_MAX")?.hora||dm.find((q:any)=>String(q.codigoParametro||"").toUpperCase()==="TA_MAX")?.instante||null);
  if(!dmin&&!dmax&&!davg){const diagnostico={hourly_station_keys:he?Object.keys(he):[],hourly_instant_keys:inst[0]?Object.keys(inst[0]):[],hourly_measure_sample:(inst[0]?.listaMedidas||inst[0]?.medidas||[]).slice(0,8),daily_top_keys:Object.keys(dj||{}),daily_station_keys:de?Object.keys(de):[],daily_measure_sample:(dm||[]).slice(0,12)};console.log("METEO_DIAG "+JSON.stringify(diagnostico));return new Response(JSON.stringify({ok:false,error:"MeteoGalicia no ofrece temperatura horaria ni resumen diario para esta estación y fecha.",diagnostico}),{status:200,headers:H});}
  return new Response(JSON.stringify({ok:true,tipo:"diario",aviso:"No hay temperatura horaria utilizable para el intervalo. Se muestran los extremos del día.",estacion:{id:est.idEstacion,nombre:est.estacion},temperatura_min:dmin?.v??null,hora_temperatura_min:hmin,temperatura_max:dmax?.v??null,hora_temperatura_max:hmax,temperatura_media:davg?.v??null,precipitacion:dpp?.v??null,viento_medio:dwa?.v??null,viento_max:dwm?.v??null}),{headers:H});
 }
 const winds=rango.map((x:any)=>val(x.listaMedidas||[],["VV_AVG","VV","V_AVG"])).filter(Boolean) as any[];const gusts=rango.map((x:any)=>val(x.listaMedidas||[],["VV_MAX","V_MAX"])).filter(Boolean) as any[];const pps=rango.map((x:any)=>val(x.listaMedidas||[],["PP_SUM","PP"])).filter(Boolean) as any[];
 const conv=(q:any)=>q&&/m\/s/i.test(q.u)?q.v*3.6:q?.v;const avg=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
 const mn=temps.length?temps.reduce((a:any,x:any)=>x.v<a.v?x:a):null,mx=temps.length?temps.reduce((a:any,x:any)=>x.v>a.v?x:a):null;
 return new Response(JSON.stringify({ok:true,tipo:"horario",estacion:{id:est.idEstacion,nombre:est.estacion},lecturas:rango.length,temperatura_min:mn?.v??null,hora_temperatura_min:mn?madrid(mn.d):null,temperatura_max:mx?.v??null,hora_temperatura_max:mx?madrid(mx.d):null,temperatura_media:avg(temps.map(x=>x.v)),lecturas_temperatura:temps.map(x=>({hora:madrid(x.d),temperatura:x.v})),precipitacion:pps.length?pps.reduce((s,x)=>s+x.v,0):null,viento_medio:avg(winds.map(conv)),viento_max:gusts.length?Math.max(...gusts.map(conv)):(winds.length?Math.max(...winds.map(conv)):null)}),{headers:H});
}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:String(e)}),{status:200,headers:H})}});