name: Build config
on:
  push:
    branches: [fix/configuracion-dependencias-react]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
